### ISSUE TITLE
Consider using conda-forge PDAL

### ISSUE THREAD

**Issue by msmolens** [OpenDataAnalytics/kitware-geospatial-recipes#14]
PDAL is now available on conda-forge:
- https://github.com/conda-forge/pdal-feedstock
- https://anaconda.org/conda-forge/pdal

Consider removing the pdal/libpdal packages from the kitware-geospatial channel and ensuring that the recipes in this repo are compatible with the conda-forge packages. This would avoid continued maintenance of the pdal recipe and packages.

**Comment by danlipsa** [comment]
libpdal does not seem to be available on conda-forge. Not sure what library is this conda-forge python library is suppose to use.

**Comment by msmolens** [comment]
The pdal package on conda-forge contains the C++ libraries and applications. See discussion here:
https://github.com/conda-forge/pdal-feedstock/issues/21

It looks like the Python package is not yet available on conda-forge, but may be available soon:
https://github.com/PDAL/python/issues/1

**Comment by danlipsa** [comment]
Sounds good. We can check back in a month or so.
