### ISSUE TITLE
LAZ libs

### ISSUE THREAD

**Issue by mccarthyryanc** [OpenDataAnalytics/kitware-geospatial-recipes#8]
Any plans to tie in LASzip or LAZperf for LAZ support in PDAL? Thanks for setting up this recipe, +1 for python 3.6 support.

**Comment by danlipsa** [comment]
Not at the moment, as we don't have a need for it in our current use.

**Comment by mccarthyryanc** [comment]
No problem, thanks for the feedback!

**Comment by chambbj** [comment]
@mccarthyryanc I've started putting together a bare bones PDAL condo recipe destined for condo-forge. The first cut doesn't have LAZ support, but it would definitely be in the roadmap. I think we'd try to turn on as many of the plugins and optional dependencies as possible.

@danlipsa I see that your repo is also targeted for condo-forge. We'll have to deconflict at some point and make sure we don't step on one another's toes. FWIW, I was not making a distinction between `libpdal` and `pdal`. I've got one recipe that will build both (though we have discussed breaking the PDAL python package out as it's own repo at some point in the future). Do you have a compelling reason to package them separately (considering that `libpdal` would be required anywhere you installed `pdal` anyway)?
